/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    products: Product;
    customers: Customer;
    'customer-addresses': CustomerAddress;
    orders: Order;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    customers: {
      addresses: 'customer-addresses';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    'customer-addresses': CustomerAddressesSelect<false> | CustomerAddressesSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'operator';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Заполняется автоматически из названия, но его можно отредактировать вручную.
   */
  slug: string;
  description?: string | null;
  image?: (number | null) | Media;
  isActive?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  /**
   * Заполняется автоматически из названия, но его можно отредактировать вручную.
   */
  slug: string;
  category: number | Category;
  status: 'active' | 'hidden' | 'out_of_stock';
  /**
   * Цена в рублях.
   */
  price: number;
  oldPrice?: number | null;
  description?: string | null;
  image?: (number | null) | Media;
  details?: {
    weightGrams?: number | null;
    portionSize?: string | null;
    ingredients?: string | null;
    nutrition?: {
      servingBasis?: ('per_100g' | 'per_serving') | null;
      caloriesKcal?: number | null;
      proteinGrams?: number | null;
      fatGrams?: number | null;
      carbsGrams?: number | null;
    };
    /**
     * От 0 до 5.
     */
    spicyLevel?: number | null;
  };
  recommendation?: {
    isRecommended?: boolean | null;
    peopleMin?: number | null;
    peopleMax?: number | null;
    /**
     * Например: хорошо подходит детям, офису, большой компании.
     */
    aiDescription?: string | null;
  };
  /**
   * Например: мясное, без свинины, детское, острое.
   */
  tags?: string[] | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  displayName: string;
  phone?: string | null;
  email?: string | null;
  /**
   * Идентификатор пользователя Telegram для связки с ботом.
   */
  telegramUserId?: string | null;
  telegramUsername?: string | null;
  /**
   * Идентификатор пользователя MAX для связки с ботом.
   */
  maxUserId?: string | null;
  maxFirstName?: string | null;
  maxLastName?: string | null;
  status: 'active' | 'new' | 'vip' | 'blocked';
  addresses?: {
    docs?: (number | CustomerAddress)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  preferences?: {
    favoriteCategories?: (number | Category)[] | null;
    dislikes?: string[] | null;
    noPork?: boolean | null;
    noSpicy?: boolean | null;
  };
  marketing?: {
    acceptsTelegramMessages?: boolean | null;
    acceptsMaxMessages?: boolean | null;
    source?: ('telegram' | 'max' | 'admin' | 'aggregator' | 'other') | null;
  };
  /**
   * Внутренние заметки для администратора.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-addresses".
 */
export interface CustomerAddress {
  id: number;
  customer: number | Customer;
  label: string;
  fullAddress: string;
  apartment?: string | null;
  intercom?: string | null;
  entrance?: string | null;
  floor?: string | null;
  comment?: string | null;
  /**
   * Если включить, остальные адреса этого клиента перестанут быть адресами по умолчанию.
   */
  isDefault?: boolean | null;
  status: 'active' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  /**
   * Генерируется автоматически при создании.
   */
  orderNumber?: string | null;
  /**
   * Используется в ссылке на корзину. Не должен быть предсказуемым.
   */
  publicToken: string;
  customer: number | Customer;
  status: 'cart' | 'submitted' | 'paid' | 'completed' | 'cancelled';
  source: 'ai' | 'manual' | 'admin' | 'reorder';
  channel: 'telegram' | 'max' | 'mini_app' | 'admin';
  /**
   * Для корзины показывает, кто последним применил изменение.
   */
  lastEditedBy?: ('ai' | 'customer' | 'admin') | null;
  items: {
    product: number | Product;
    productNameSnapshot: string;
    unitPriceSnapshot: number;
    quantity: number;
    lineTotalSnapshot: number;
    comment?: string | null;
    id?: string | null;
  }[];
  totals: {
    subtotalAmount: number;
    discountAmount?: number | null;
    deliveryAmount?: number | null;
    totalAmount: number;
  };
  delivery?: {
    address?: (number | null) | CustomerAddress;
    /**
     * Заполняется из выбранного адреса, но хранится отдельно для истории заказа.
     */
    addressSnapshot?: string | null;
    apartmentSnapshot?: string | null;
    intercomSnapshot?: string | null;
    entranceSnapshot?: string | null;
    floorSnapshot?: string | null;
    customerComment?: string | null;
    courierComment?: string | null;
    requestedAt?: string | null;
  };
  payment?: {
    method?: ('not_selected' | 'cash' | 'card_on_delivery' | 'online') | null;
    status?: ('not_required' | 'pending' | 'paid' | 'failed' | 'refunded') | null;
    provider?: string | null;
    externalPaymentId?: string | null;
  };
  ai?: {
    prompt?: string | null;
    explanation?: string | null;
    model?: string | null;
    rawResponse?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  /**
   * Для AI-предложений можно ограничить срок действия ссылки.
   */
  expiresAt?: string | null;
  submittedAt?: string | null;
  paidAt?: string | null;
  cancelledAt?: string | null;
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'customer-addresses';
        value: number | CustomerAddress;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  image?: T;
  isActive?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  category?: T;
  status?: T;
  price?: T;
  oldPrice?: T;
  description?: T;
  image?: T;
  details?:
    | T
    | {
        weightGrams?: T;
        portionSize?: T;
        ingredients?: T;
        nutrition?:
          | T
          | {
              servingBasis?: T;
              caloriesKcal?: T;
              proteinGrams?: T;
              fatGrams?: T;
              carbsGrams?: T;
            };
        spicyLevel?: T;
      };
  recommendation?:
    | T
    | {
        isRecommended?: T;
        peopleMin?: T;
        peopleMax?: T;
        aiDescription?: T;
      };
  tags?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  displayName?: T;
  phone?: T;
  email?: T;
  telegramUserId?: T;
  telegramUsername?: T;
  maxUserId?: T;
  maxFirstName?: T;
  maxLastName?: T;
  status?: T;
  addresses?: T;
  preferences?:
    | T
    | {
        favoriteCategories?: T;
        dislikes?: T;
        noPork?: T;
        noSpicy?: T;
      };
  marketing?:
    | T
    | {
        acceptsTelegramMessages?: T;
        acceptsMaxMessages?: T;
        source?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-addresses_select".
 */
export interface CustomerAddressesSelect<T extends boolean = true> {
  customer?: T;
  label?: T;
  fullAddress?: T;
  apartment?: T;
  intercom?: T;
  entrance?: T;
  floor?: T;
  comment?: T;
  isDefault?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  publicToken?: T;
  customer?: T;
  status?: T;
  source?: T;
  channel?: T;
  lastEditedBy?: T;
  items?:
    | T
    | {
        product?: T;
        productNameSnapshot?: T;
        unitPriceSnapshot?: T;
        quantity?: T;
        lineTotalSnapshot?: T;
        comment?: T;
        id?: T;
      };
  totals?:
    | T
    | {
        subtotalAmount?: T;
        discountAmount?: T;
        deliveryAmount?: T;
        totalAmount?: T;
      };
  delivery?:
    | T
    | {
        address?: T;
        addressSnapshot?: T;
        apartmentSnapshot?: T;
        intercomSnapshot?: T;
        entranceSnapshot?: T;
        floorSnapshot?: T;
        customerComment?: T;
        courierComment?: T;
        requestedAt?: T;
      };
  payment?:
    | T
    | {
        method?: T;
        status?: T;
        provider?: T;
        externalPaymentId?: T;
      };
  ai?:
    | T
    | {
        prompt?: T;
        explanation?: T;
        model?: T;
        rawResponse?: T;
      };
  expiresAt?: T;
  submittedAt?: T;
  paidAt?: T;
  cancelledAt?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}